- name: Find bash
  shell: which bash
  register: bash_location
  changed_when: false

- name: "[iptables] Check for existing IPv4 rule"
  shell: "iptables -L | grep -E '^DROP' | grep -E 'flags:SYN/SYN tcpmss match 1:500$'"
  args:
    executable: "{{ bash_location.stdout }}"
  register: iptables_check
  changed_when: false
  failed_when: iptables_check.sterr.find('command not found') != -1

- name: "[iptables] Block malicious IPv4 SACK packets"
  shell: "iptables -I INPUT -p tcp --tcp-flags SYN SYN -m tcpmss --mss 1:500 -j DROP"
  args:
    executable: "{{ bash_location.stdout }}"
  when: iptables_check.rc != 0

- name: "[iptables] Check for existing IPv6 rule"
  shell: "ip6tables -L | grep -E '^DROP' | grep -E 'flags:SYN/SYN tcpmss match 1:500$'"
  args:
    executable: "{{ bash_location.stdout }}"
  register: ip6tables_check
  changed_when: false
  failed_when: ip6tables_check.sterr.find('command not found') != -1

- name: "[iptables] Block malicious IPv6 SACK packets"
  shell: "ip6tables -I INPUT -p tcp --tcp-flags SYN SYN -m tcpmss --mss 1:500 -j DROP"
  args:
    executable: "{{ bash_location.stdout }}"
  when: ip6tables_check.rc != 0
